with open(r'C:\Users\codyb\WebstormProjects\Rubber Tracker\src\Code.gs', 'r', encoding='utf-8') as f:
    content = f.read()

search = 'promptPurgeTaskByLocation'
idx = content.find(search)
while idx >= 0:
    line_start = content.rfind('\n', 0, idx) + 1
    line_end = content.find('\n', idx)
    line = content[line_start:line_end]
    if 'addItem' in line:
        print('Found addItem at char:', idx)
        print('Line repr:', repr(line))
        break
    idx = content.find(search, idx + 1)

# Also check if cleanup function was added
if 'cleanupAutoGeneratedCertTasksFromManualTasks' in content:
    print('Cleanup function present: YES')
else:
    print('Cleanup function present: NO')

# Check if generateToDoTasksFromCerts is disabled
if 'generateToDoTasksFromCerts: DISABLED' in content:
    print('generateToDoTasksFromCerts disabled: YES')
else:
    print('generateToDoTasksFromCerts disabled: NO')

# Count emojis
import re
emojis = re.findall(r'[\U0001F000-\U0001FFFF]', content)
print('Emoji count:', len(emojis))

