#!/usr/bin/env python3
"""
Scan all .gs and .html files in src/ for CP1252 mojibake and fix them.

Mojibake: UTF-8 bytes were decoded as Windows-1252 (CP1252), then the
resulting characters were re-saved as UTF-8.  Reversing it:
  garbled_text.encode('cp1252').decode('utf-8')  -> original text

Examples of what needs fixing:
  ðŸ"  ->  🔍   (or whatever emoji it decodes to)
  â€¢  ->  •
  âœ…  ->  ✅
  â ï¸  ->  ⚠️
  ðŸ—'ï¸  ->  🗑️
  â±ï¸  ->  ⏱️
"""

import os

SRC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src')

# Known mojibake -> correct mappings (CP1252 mojibake of common emoji/chars)
# Generated by: char.encode('utf-8').decode('cp1252') for common chars
REPLACEMENTS = []

def build_replacements():
    """Build a list of (mojibake_str, correct_str) pairs for common chars."""
    chars = [
        # Emoji commonly used in this project
        '\U0001F4CB',  # 📋
        '\U0001F50D',  # 🔍
        '\U0001F5D1\uFE0F',  # 🗑️
        '\U000023F1\uFE0F',  # ⏱️
        '\u2705',      # ✅
        '\u26A0\uFE0F',  # ⚠️
        '\U0001F4CA',  # 📊
        '\U0001F4C5',  # 📅
        '\U0001F3AF',  # 🎯
        '\U0001F6D2',  # 🛒
        '\U0001F6E1\uFE0F',  # 🛡️
        '\U0001F4E5',  # 📥
        '\U0001F527',  # 🔧
        '\U0001F9F9',  # 🧹
        '\U0001F4DD',  # 📝
        '\U0001F680',  # 🚀
        '\U0001F4BE',  # 💾
        '\U0001F4C2',  # 📂
        '\U0001F4C8',  # 📈
        '\U0001F5FA\uFE0F',  # 🗺️
        '\U0001F477',  # 👷
        '\U0001F4DE',  # 📞
        '\u2709\uFE0F',  # ✉️
        '\U0001F4A1',  # 💡
        '\U0001F514',  # 🔔
        '\U0001F3E5',  # 🏥
        '\U0001F9BD',  # 🧽
        '\U0001F389',  # 🎉
        '\U0001F44D',  # 👍
        '\u274C',      # ❌
        '\U0001F504',  # 🔄
        '\U0001F534',  # 🔴
        '\U0001F7E0',  # 🟠
        '\U0001F7E1',  # 🟡
        '\U0001F7E2',  # 🟢
        '\U0001F512',  # 🔒
        '\U0001F195',  # 🆕
        '\U0001F6A8',  # 🚨
        '\U0001F4CC',  # 📌
        '\U0001F4AC',  # 💬
        '\U0001F511',  # 🔑
        '\U0001F3E8',  # 🏨
        '\U0001F3E2',  # 🏢
        '\U0001F513',  # 🔓
        '\U0001F4CD',  # 📍
        '\U0001F5D3\uFE0F',  # 🗓️
        '\U0001F393',  # 🎓
        '\u2022',      # • (bullet)
        '\u2713',      # ✓
        '\u2714',      # ✔
        '\u2192',      # →
        '\u2714\uFE0F',  # ✔️
        '\U0001F4E7',  # 📧
        '\U0001F4E4',  # 📤
        '\U0001F4E3',  # 📣
        '\u2139\uFE0F',  # ℹ️
        '\U0001F4AF',  # 💯
        '\U0001F6AB',  # 🚫
        '\u2714',      # ✔
        '\U0001F3D7\uFE0F',  # 🏗️
        '\U0001F4E6',  # 📦
        '\U0001F465',  # 👥
        '\U0001F4BB',  # 💻
        '\u2728',      # ✨
        '\U0001F440',  # 👀
        '\u2764\uFE0F',  # ❤️
        '\U0001F6A7',  # 🚧
        '\U0001F4F1',  # 📱
        '\U0001F4B0',  # 💰
        '\U0001F4B3',  # 💳
        '\U0001F4B5',  # 💵
        '\u23F0',      # ⏰
        '\u23F3',      # ⏳
        '\u2615',      # ☕
        '\U0001F4A4',  # 💤
        '\u2705',      # ✅ (already above but ok)
        '\u274E',      # ❎
        '\U0001F553',  # 🕓
        '\U0001F4C6',  # 📆
        '\U0001F4C7',  # 📇
        '\U0001F4C9',  # 📉
        '\U0001F4D1',  # 📑
        '\U0001F4D2',  # 📒
        '\U0001F4D3',  # 📓
        '\U0001F4D4',  # 📔
        '\U0001F4D5',  # 📕
        '\U0001F4D6',  # 📖
        '\U0001F4D7',  # 📗
        '\U0001F4D8',  # 📘
        '\U0001F4D9',  # 📙
        '\U0001F4DA',  # 📚
        '\U0001F4E1',  # 📡
        '\U0001F4E2',  # 📢
        '\u26A1',      # ⚡
        '\u2B50',      # ⭐
        '\U0001F4AA',  # 💪
    ]
    pairs = []
    seen = set()
    for c in chars:
        if c in seen:
            continue
        seen.add(c)
        try:
            mojibake = c.encode('utf-8').decode('cp1252')
            if mojibake != c:  # Only add if it actually changes
                pairs.append((mojibake, c))
        except (UnicodeDecodeError, UnicodeEncodeError):
            pass
    # Sort longest first to avoid partial replacements
    pairs.sort(key=lambda x: -len(x[0]))
    return pairs

def scan_and_fix(dry_run=False):
    replacements = build_replacements()
    print(f'Built {len(replacements)} mojibake->correct mappings')

    total_files = 0
    total_changes = 0

    for fn in sorted(os.listdir(SRC_DIR)):
        if not (fn.endswith('.gs') or fn.endswith('.html')):
            continue
        path = os.path.join(SRC_DIR, fn)
        with open(path, 'r', encoding='utf-8') as f:
            original = f.read()

        fixed = original
        file_changes = 0
        for bad, good in replacements:
            count = fixed.count(bad)
            if count > 0:
                fixed = fixed.replace(bad, good)
                file_changes += count

        if file_changes > 0:
            total_files += 1
            total_changes += file_changes
            print(f'  {"[DRY RUN] Would fix" if dry_run else "FIXED"} {fn}: {file_changes} replacements')
            if not dry_run:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(fixed)

    if total_files == 0:
        print('No mojibake found in any .gs or .html file.')
    else:
        action = 'Would fix' if dry_run else 'Fixed'
        print(f'\n{action} {total_changes} mojibake instances across {total_files} files.')

if __name__ == '__main__':
    import sys
    dry = '--dry-run' in sys.argv or '-n' in sys.argv
    if dry:
        print('=== DRY RUN - no files will be modified ===\n')
    scan_and_fix(dry_run=dry)
