with open(r'C:\Users\codyb\WebstormProjects\Rubber Tracker\src\Code.gs', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the Purge line (with its stray \x8f char) and replace cleanly
search = 'promptPurgeTaskByLocation'
idx = content.find(search)
while idx >= 0:
    line_start = content.rfind('\n', 0, idx) + 1
    line_end = content.find('\n', idx)
    line = content[line_start:line_end]
    if 'addItem' in line:
        # Replace this entire line with clean version + new item
        # Use triple closing ))) -> ) for Purge line, new cert line gets )))
        new_line = "        .addItem('\U0001f5d1\ufe0f Purge Stuck Task by Location', 'promptPurgeTaskByLocation')\n        .addItem('\U0001f5d1\ufe0f Remove Auto-Generated Cert Tasks', 'cleanupAutoGeneratedCertTasksFromManualTasks')))"
        content = content[:line_start] + new_line + content[line_end:]
        print('CHANGE 3 (with stray char fix): Menu item added - OK')
        break
    idx = content.find(search, idx + 1)

with open(r'C:\Users\codyb\WebstormProjects\Rubber Tracker\src\Code.gs', 'w', encoding='utf-8') as f:
    f.write(content)

print('File saved.')

# Verify
with open(r'C:\Users\codyb\WebstormProjects\Rubber Tracker\src\Code.gs', 'r', encoding='utf-8') as f:
    content2 = f.read()

idx2 = content2.find('promptPurgeTaskByLocation')
while idx2 >= 0:
    line_start = content2.rfind('\n', 0, idx2) + 1
    line_end = content2.find('\n', idx2)
    line = content2[line_start:line_end]
    if 'addItem' in line:
        print('Purge line:', repr(line))
        # Check next line
        next_line_start = line_end + 1
        next_line_end = content2.find('\n', next_line_start)
        print('Next line:', repr(content2[next_line_start:next_line_end]))
        break
    idx2 = content2.find('promptPurgeTaskByLocation', idx2 + 1)

