#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Re-apply the 3 Code.gs changes from the May 20 session using proper UTF-8 handling.
1. Disable generateToDoTasksFromCerts() with early return
2. Add cleanupAutoGeneratedCertTasksFromManualTasks() function
3. Add menu item for it under Review & Schedule > Utilities
"""

FILE = r'C:\Users\codyb\WebstormProjects\Rubber Tracker\src\Code.gs'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# =============================================
# CHANGE 1: Disable generateToDoTasksFromCerts
# =============================================
OLD_FUNC_START = 'function generateToDoTasksFromCerts(certRows, selectedCertTypes, empMap, skipTaskGeneration) {'
NEW_FUNC_START = 'function generateToDoTasksFromCerts(certRows, selectedCertTypes, empMap, skipTaskGeneration) {\n  // DISABLED: Task Metadata now handles cert expiration tracking via collectExpiringCertTasks().\n  // The Manual Tasks sheet is for user-created tasks only. This function wrote misaligned\n  // data (12-column array into a 15-column sheet) and created duplicate cert tasks.\n  Logger.log(\'generateToDoTasksFromCerts: DISABLED - cert tasks handled by Task Metadata pipeline\');\n  return 0;'

if OLD_FUNC_START in content:
    content = content.replace(OLD_FUNC_START, NEW_FUNC_START, 1)
    print('CHANGE 1: generateToDoTasksFromCerts disabled - OK')
else:
    print('CHANGE 1: WARNING - generateToDoTasksFromCerts function header not found!')

# =============================================
# CHANGE 2: Add cleanupAutoGeneratedCertTasksFromManualTasks() after generateToDoTasksFromCerts
# =============================================
NEW_CLEANUP_FUNCTION = '''

/**
 * Removes auto-generated cert renewal rows from the Manual Tasks sheet.
 * These rows were added by the now-disabled generateToDoTasksFromCerts() function
 * and have misaligned column data (expiration date in Employee column, etc.).
 * Identifies them by: Task Type (col C) starts with "Renew " AND
 * Date Added (col J) starts with "Employee:" (the misaligned notes text).
 */
function cleanupAutoGeneratedCertTasksFromManualTasks() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('Manual Tasks');
  if (!sheet) {
    SpreadsheetApp.getUi().alert('Manual Tasks sheet not found.');
    return;
  }
  var data = sheet.getDataRange().getValues();
  var rowsToDelete = [];
  for (var i = 1; i < data.length; i++) {
    var taskType = String(data[i][2] || '');   // col C = index 2
    var dateAdded = String(data[i][9] || '');  // col J = index 9
    if (taskType.indexOf('Renew ') === 0 && dateAdded.indexOf('Employee:') === 0) {
      rowsToDelete.push(i + 1); // 1-based row number
    }
  }
  // Delete from bottom to top to preserve row indices
  for (var j = rowsToDelete.length - 1; j >= 0; j--) {
    sheet.deleteRow(rowsToDelete[j]);
  }
  Logger.log('cleanupAutoGeneratedCertTasksFromManualTasks: Deleted ' + rowsToDelete.length + ' rows');
  var msg = rowsToDelete.length > 0
    ? 'Removed ' + rowsToDelete.length + ' auto-generated cert task rows from Manual Tasks.'
    : 'No auto-generated cert rows found - Manual Tasks is clean.';
  SpreadsheetApp.getUi().alert(msg);
}'''

# Insert it right before the line "// =====================" or similar that follows generateToDoTasksFromCerts.
# Find a good anchor: the function after generateToDoTasksFromCerts
# We'll insert right before "function generateScheduleFromToDoList" or similar.
# Actually, let's just append it after the disabled function block ends.
ANCHOR = '// === END TASK GENERATION FUNCTIONS ==='
if ANCHOR not in content:
    # Use a different anchor - find what comes right after generateToDoTasksFromCerts function
    # Just add it before "function openToDoListDialog" or similar
    ANCHOR2 = '\nfunction openToDoListDialog'
    if ANCHOR2 in content:
        content = content.replace(ANCHOR2, NEW_CLEANUP_FUNCTION + ANCHOR2, 1)
        print('CHANGE 2: cleanupAutoGeneratedCertTasksFromManualTasks added - OK (anchor2)')
    else:
        # As last resort, find any function that likely follows the certs section
        # Look for the section break or the next function
        import re
        # Find position right after the generateToDoTasksFromCerts function ends
        func_start = content.find('function generateToDoTasksFromCerts(')
        # Find the closing brace (next top-level function)
        next_func = content.find('\nfunction ', func_start + 100)
        if next_func > 0:
            content = content[:next_func] + NEW_CLEANUP_FUNCTION + content[next_func:]
            print('CHANGE 2: cleanupAutoGeneratedCertTasksFromManualTasks added - OK (next_func)')
        else:
            print('CHANGE 2: ERROR - could not find insertion point!')
else:
    content = content.replace(ANCHOR, NEW_CLEANUP_FUNCTION + '\n' + ANCHOR, 1)
    print('CHANGE 2: cleanupAutoGeneratedCertTasksFromManualTasks added - OK (anchor)')

# =============================================
# CHANGE 3: Add menu item in Review & Schedule > Utilities
# =============================================
OLD_MENU = ".addItem('\U0001f5d1\ufe0f Purge Stuck Task by Location', 'promptPurgeTaskByLocation')))"
NEW_MENU = ".addItem('\U0001f5d1\ufe0f Purge Stuck Task by Location', 'promptPurgeTaskByLocation')\n        .addItem('\U0001f5d1\ufe0f Remove Auto-Generated Cert Tasks', 'cleanupAutoGeneratedCertTasksFromManualTasks')))"

if OLD_MENU in content:
    content = content.replace(OLD_MENU, NEW_MENU, 1)
    print('CHANGE 3: Menu item added - OK')
else:
    # Try without the emoji - maybe different emoji char
    print('CHANGE 3: Exact emoji not matched, searching for text...')
    idx = content.find("'promptPurgeTaskByLocation')))")
    if idx >= 0:
        print('Found at char:', idx)
        print('Context:', repr(content[idx-50:idx+80]))
    else:
        print('CHANGE 3: ERROR - could not find menu line!')

# Save
with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print('File saved.')

